## InfinityExpansion2 main configuration file
## Visit wiki for more details: https://docs.ybw0014.dev/infinity-expansion-2/config/main

# You should enable this to get bug fixes and receive support
auto-update: true

# The default language of the plugin
# SlimefunTranslation is supported.
lang: en

# Whether to enable researches in the plugin
enable-researches: false

# Debug options
debug:
  # Whether to enable debug logs
  enabled: false

  # Debug cases that are enabled at startup
  # Available debug cases: INFINITY_MATRIX, QUARRY, MOB_SIMULATION, STORAGE, SINGULARITY,
  #                        GEAR_TRANSFORMER, RESOURCE_SYNTHESIZER, ADVANCED_ANVIL, NETWORK, TICK
  # You can also toggle these in-game using /ie debug <enable|disable|toggle> <case>
  # Case names are case-insensitive
  cases: []

# Singularity options
singularity:
  # The global cost multiplier for singularity crafting
  # range: 0.0 to 1000.0, default: 1.0
  cost-multiplier: 1.0

# Gear transformer options
gear-transformer:
  # Can Gear Transformer transform slimefun gear's material.
  # Diamond tools can already be upgraded to netherite in smithing table.
  # but some addon developers do not want their gear to be transformable, so change this at your own risk.
  allow-sf-items: false

# Resource synthesizer options
resource-synthesizer:
  # Each entry is a recipe.
  #
  # The input and output item must be a valid Slimefun item, or the recipe will be ignored.
  # All the infinity expansion 2 item has the prefix IE_.
  #
  # The output amount can be omitted and default to 1.
  #
  # Usually, you should use singularity as the input, but you can use any Slimefun item.
  # The machine only checks ID of the input item, so do not use complex items.
  recipes:
    - input:
        1: IE_IRON_SINGULARITY
        2: IE_COAL_SINGULARITY
      output:
        item: REINFORCED_ALLOY_INGOT
        amount: 32
    - input:
        1: IE_DIAMOND_SINGULARITY
        2: IE_COAL_SINGULARITY
      output:
        item: CARBONADO
        amount: 16
    - input:
        1: IE_GOLD_SINGULARITY
        2: IE_EMERALD_SINGULARITY
      output:
        item: BLISTERING_INGOT_3
        amount: 16
    - input:
        1: IE_COPPER_SINGULARITY
        2: IE_ZINC_SINGULARITY
      output:
        item: ELECTRO_MAGNET
        amount: 64
    - input:
        1: IE_IRON_SINGULARITY
        2: IE_QUARTZ_SINGULARITY
      output:
        item: SOLAR_PANEL
        amount: 64

# Mob simulation options
# Customize all data cards in mob-simulation.yml
mob-simulation:

  # The amount of runs required to output once (affected by tick rate)
  # Range: 1 to 3600
  output-interval: 20

  # Whether cards can be stackable.
  # When enabled, the product will be multiplied by the amount of cards. The energy consumption is also multiplied.
  # When disabled, multiple cards always produce 1x.
  # Tip: when enabled, you may have to change the energy capacity of Mob Simulation Chamber accordingly,
  #   since stacked cards may exceed the energy capacity and the chamber will always complain about not enough energy.
  allow-stacked-card: false

  # The multiplier for the experience given by mob simulation.
  # range: 0.0 to 1000.0, default: 1.0
  exp-multiplier: 1.0

  # Whether to use the legacy output mode in InfinityExpansion.
  # Legacy V1 mode: The chance of each drop is its weight, and each time the simulation will randomly choose 1 drop from the pool.
  # V2 mode: Each drop has a chance to be dropped.
  legacy-output: false

# Storage options
storage:
  # Whether the signs attached to the storage units will show the item and amount inside the storage?
  # Enabling this will increase the server's load, enabling extra tickers on main thread.
  enable-signs: false

  # The interval of updating the signs in Slimefun ticks.
  sign-update-interval: 20

  # Whether the storage units will display the item and amount inside the storage in the hologram?
  # The holograms require the external library
  # Enabling this will increase the server's load, enabling extra tickers on main thread.
  enable-holograms: false

  # The interval of updating the holograms in Slimefun ticks.
  hologram-update-interval: 20

  # The list of additional items that cannot be stored into storage units.
  # This will not affect the items that are already stored, but new items cannot be stored.
  # Bundles, shulker boxes, and IE2 Storage Units are hardcoded blocked and cannot be changed.
  #
  blocked-items: []

# Quarry options
quarry:
  # The amount of runs required to output once (affected by tick rate)
  # Range: 1 to 3600
  output-interval: 10

  # The product pool of all the quarries
  # There are 3 world environments: normal, nether, the_end
  # A quarry's products are determined by the environment it is in.
  # The quarry wiki page has a detailed explanation of how the quarry works, it may help you understand the pool.
  #
  # All the item IDs must be a valid Material, or a valid Slimefun item ID.
  #
  # Due to how the config file is processed, you cannot remove pre-defined fields.
  # If you want to "remove" a pre-defined item from the pool, set its weight to 0.
  pools:
    normal:
      base-product: COBBLESTONE
      products:
        COAL: 4
        COPPER_INGOT: 2
        IRON_INGOT: 1
        GOLD_INGOT: 1
        REDSTONE: 1
        LAPIS_LAZULI: 1
        EMERALD: 1
        DIAMOND: 1
    nether:
      base-product: NETHERRACK
      products:
        GOLD_INGOT: 3
        QUARTZ: 1
        NETHERITE_INGOT: 1
    the_end:
      base-product: END_STONE
      products:
        OBSIDIAN: 1

  # The chance (0 to 1) of an oscillator activating each time a material would be produced
  # The materials listed here will be registered as oscillators.
  # You can add more oscillators. The key must be a valid material ID, or a valid Slimefun item ID.
  #
  # Due to how the config file is processed, you cannot remove pre-defined fields.
  # If you want to "remove" a pre-defined oscillator, set its chance to 0.
  oscillators:
    LAPIS_LAZULI: .5
    DIAMOND: .5
    REDSTONE: .5
    QUARTZ: .5
    EMERALD: .5
    COAL: .5
    GOLD_INGOT: .5

# The maximum possible level of every enchantment in advanced anvil
# all the keys are the key part of an Enchantment's NamespacedKey
# Enchantment: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
# Enchantments not defined here will have the vanilla level limit.
#
# Due to how the config file is processed, you cannot remove pre-defined fields.
# If you want to "remove" a pre-defined enchantment, set its level to 0. It will be read as not set, thus will have its vanilla limit.
#
# after 1.20.5, bukkit renamed the naming of Enchantment enum, so the name is the same as the key part except case.
# so, you only need to turn the Enchantment's name into lowercase.
# e.g. FIRE_ASPECT -> fire_aspect
advanced-anvil:
  max-levels:
    sharpness: 9
    bane_of_arthropods: 9
    smite: 9
    protection: 10
    fortune: 6
    efficiency: 7
    fire_aspect: 6
    power: 7
    thorns: 13
    looting: 6
    unbreaking: 13

# Infinity gear options
#
# Each section represents a type of gear, and each section has the following sub-sections:
# - `unbreakable`: Whether the gear is unbreakable.
# - `enchantments`: A map of enchantments and their levels.
# - `potion-effects`: (Only works on armor) A map of potion effects and their amplifiers.
# - `protections`: (Only works on armor) A list of protection types.
#
# Due to how the config file is processed, you cannot remove pre-defined fields.
#
# Enchantment: https://jd.papermc.io/paper/1.20.6/org/bukkit/enchantments/Enchantment.html (change the version in url to match your server version)
# To disable a pre-defined enchantment, set its level to 0.
#
# PotionEffectType: https://jd.papermc.io/paper/1.20.6/org/bukkit/potion/PotionEffectType.html
# The amplifier represents is how many levels added to the potion effect. (e.g. haste: 2 means Haste III in game)
# To disable a pre-defined potion effect, set its amplifier to a negative number (like -1).
#
# ProtectionType: https://github.com/GuizhanCraft/InfinityExpansion2/blob/master/src/main/kotlin/net/guizhanss/infinityexpansion2/core/items/attributes/ProtectionType.kt
#
# Changing `unbreakable` and `enchantments` will only affect new gears, not the already made gears.
# Changing `potion-effects` and `protections` affect both pre-defined and new gears.
#
infinity-gear:
  sword:
    unbreakable: true
    enchantments:
      sharpness: 20
      looting: 10
      fire_aspect: 10
  pickaxe:
    unbreakable: true
    enchantments:
      efficiency: 40
      fortune: 20
  shovel:
    unbreakable: true
    enchantments:
      efficiency: 40
      silk_touch: 10
  axe:
    unbreakable: true
    enchantments:
      efficiency: 40
      sharpness: 20
      fire_aspect: 10
      looting: 0
      silk_touch: 0
  hoe:
    unbreakable: true
    enchantments:
      efficiency: 40
      fortune: 20
      silk_touch: 0
  fishing_rod:
    unbreakable: true
    enchantments:
      luck_of_the_sea: 10
      lure: 10
  bow:
    unbreakable: true
    enchantments:
      power: 10
      flame: 10
      infinity: 10
      punch: 0
  crossbow:
    unbreakable: true
    enchantments:
      power: 10
      punch: 0
      piercing: 5
      multishot: 10
      quick_charge: 5
  helmet:
    unbreakable: true
    enchantments:
      protection: 20
      aqua_affinity: 10
    potion-effects:
      night_vision: 0
      conduit_power: 0
    protections:
      - "flying_into_wall"
  chestplate:
    unbreakable: true
    enchantments:
      protection: 20
      thorns: 10
    potion-effects:
      resistance: 0
      fire_resistance: 0
      strength: 1
    protections:
      - "bees"
  leggings:
    unbreakable: true
    enchantments:
      protection: 20
      thorns: 10
    potion-effects:
      haste: 2
      regeneration: 0
      saturation: 0
    protections:
      - "radiation"
  boots:
    unbreakable: true
    enchantments:
      protection: 20
      feather_falling: 0
      thorns: 0
    potion-effects:
      speed: 2
      dolphins_grace: 0
    protections:
      - "fall"
  shield:
    unbreakable: true
    enchantments:
      protection: 20
      thorns: 10

## Some InfinityExpansion2 items have their extra config options in Items.yml, check the wiki for more information.
